---
mobile_form_factors:
  - 'Portable'
  - 'Laptop'
  - 'Notebook'
  - 'Sub Notebook'
  - 'Tablet'
  - 'Convertible'
  - 'Detachible'
  - 'Hand Held'

rhel8_packages_common:
  - tmux
  - irssi
  - mutt
  - git
  - vim-enhanced
  - aspell
  - aspell-en
  - jq
  - python27
  - python36
  - python38
  - python2-virtualenv
  - python3-virtualenv
  - python3-bcc
  - python3-firewall
  - bpftrace
  - bpftool
  - bcc
  - bcc-tools
  - ruby
  - nodejs
  - gcc
  - gcc-c++
  - automake
  - autoconf
  - make
  - cmake
  - libtool
  - setools-console
  - policycoreutils-python-utils
  - setroubleshoot
  - setroubleshoot-plugins
  - setroubleshoot-server
  - krb5-workstation
  - pcp-system-tools
  - lm_sensors
  - tuned
  - tuned-utils
  - powertop
  - iotop
  - procps-ng
  - crypto-policies
  - firewalld
  - virt-manager
  - virt-viewer
  - fuse-overlayfs
  - selinux-policy-doc
  - vinagre
  - toolbox
  - nmap
  - flatpak
  - firefox
  - '@rpm-development-tools'
  - '@go-toolset:rhel8'
  - '@container-tools:rhel8'

rhel8_packages_kde:
  - "@base-x"

rhel8_packages_gnome:
  - gnome-tweaks
  - gnome-shell-extension-windowsNavigator

csb8_packages_common:
  - oneplay-gstreamer-codecs-pack
  - ffmpeg-libs
  - redhat-internal-flash-plugin
  - redhat-internal-openvpn-profiles
  - redhat-internal-NetworkManager-openvpn-profiles
  - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
  - redhat-internal-wireless-config
  - redhat-internal-cert-install

epel8_packages_common:
  - mock
  - htop
  - mosh
  - tig
  - NetworkManager-openvpn
  - fedpkg
  - fpaste
  - ack
  - earlyoom
  - xsel
  - terminus-fonts
  - glances

epel8_packages_gnome:
  - gnome-shell-extension-system-monitor-applet
  - NetworkManager-openvpn-gnome

epel8_packages_kde:
  - "@kde-desktop-environment"
  - okular
  - ark
  - sddm
  - terminus-fonts
