---
- name: Fedora Rawhide XFCE Spin - System Stuff
  hosts: localhost
  vars:
    non_root_user: admiller
  tasks:
    - name: Package Install
      yum:
        state: present
        name:
          - tmux
          - xsel
          - irssi
          - mutt
          - git
          - tig
          - vim-enhanced
          - jq
          - python3
          - python3-devel
          - python3-virtualenv
          - python3-ipython
          - python3-bpython
          - strace
          - bpftrace
          - bpftool
          - bcc
          - bcc-tools
          - python3-bcc
          - ruby
          - nodejs
          - golang
          - gcc
          - gcc-c++
          - automake
          - autoconf
          - make
          - libtool
          - setools-console
          - policycoreutils-python-utils
          - setroubleshoot-server
          - flatpak
          - flatpak-spawn
          - krb5-workstation
          - pcp-system-tools
          - lm_sensors
          - tuned
          - tuned-utils
          - powertop
          - iotop
          - procps-ng
          - firewalld
          - python3-firewall
          - virt-manager
          - virt-viewer
          - redshift
          - redshift-gtk
          - geoclue2
          - mock
          - htop
          - glances
          - NetworkManager
          - NetworkManager-openvpn
          - NetworkManager-wifi
          - fedpkg
          - fpaste
          - fedfind
          - mosh
          - flamegraph
          - fuse-overlayfs
          - podman
          - podman-docker
          - buildah
          - skopeo
          - fwupd
          - ibm-plex-mono-fonts
          - xfce4-screensaver
          - xfce4-panel-profiles
          - firefox
          - chromium
          - '@rpm-development-tools'

    - name: Package Removal
      yum:
        state: absent
        name:
          - xscreensaver
          - xscreensaver-base
          - xscreensaver-extras
          - xscreensaver-extras-base
          - xscreensaver-gl-base
          - xscreensaver-gl-extras

    - name: Ensure SELinux Enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Ensure slub_debug=- is set for GRUB_CMDLINE_LINUX
      lineinfile:
        path: /etc/sysconfig/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: GRUB_CMDLINE_LINUX="slub_debug=-"
        state: present

    - name: Enable container_manage_cgroup for running systemd in podman containers
      seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true

    - name: U2F Token udev rules
      copy:
        src: files/70-u2f.rules
        dest: /etc/udev/rules.d/70-u2f.rules
      notify:
        - reload udev

    - name: Set container registry settings
      copy:
        src: files/registries.conf
        dest: /etc/containers/registries.conf

    - name: start and enable tuned
      service:
        name: tuned
        state: started
        enabled: true

    - name: Disable ssh because reasons
      service:
        name: sshd
        state: stopped
        enabled: false

    - name: Ensure various ports are not open
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - cockpit
        - ssh

    - name: Make sure admiller user is in mock
      user:
        name: admiller
        groups: mock
        append: yes

    - name: Allow non-root user access to libvirt via polkit
      template:
        src: templates/non_root_user_libvirt_polkit.j2
        dest: /etc/polkit-1/rules.d/50-org.libvirt.unix.manage.rules
      notify:
        - reload polkit

    - name: Allow non-root user access to NetworkManager
      template:
        src: templates/network_manager_polkit.j2
        dest: /etc/polkit-1/rules.d/10-network-manager.pkla
      notify:
        - reload polkit

#### This seems like a bad idea on a SBC with mmc storage
#   - name: enable journald persistent storage
#     file:
#       path: /var/log/journal
#       state: directory

  handlers:
    - name: reload udev
      shell: /usr/sbin/udevadm control --reload
    - name: reload polkit
      service:
        name: polkit
        state: restarted

- name: Fedora Rawhide ARM XFCE Spin - User Stuff
  hosts: localhost
  become_user: admiller
  become: yes
  vars:
    xfce4_panel_profile: admiller_xfce4_4.14_panel_profile.tar.bz2
    xfce4_panel_profile_dest: "/home/{{ ansible_user_id }}/{{ xfce4_panel_profile }}"
    xfce4_terminal_conf_dir: "/home/{{ ansible_user_id }}/.config/xfce4/terminal/"
  tasks:
    - name: import user dev stuff
      import_tasks: include_tasks/user_stuff.yml

    - name: copy xfce4-panel-profile backup
      copy:
        src: "files/{{ xfce4_panel_profile }}"
        dest: "{{ xfce4_panel_profile_dest }}"

    - name: copy xfconf settings script over
      copy:
        src: files/xfce-4.14-xfconf-settings.sh
        dest: "/home/{{ ansible_user_id }}/xfconf-settings.sh"
        mode: "u+rwx"

    - name: ensure xfce4-terminal config dir exists
      file:
        path: "{{ xfce4_terminal_conf_dir }}"
        state: directory

    - name: copy xfce4-terminal terminalrc into homedir
      copy:
        src: files/terminalrc
        dest: "{{ xfce4_terminal_conf_dir }}/terminalrc"

