---
# NOTE: This system must first be bootstrapped with the following:
# 
# sudo rpm-ostree install tmux vim-enhanced ansible powertop xsel
- name: Fedora 34 Silverblue
  hosts: localhost
  vars:
    non_root_user: admiller
    rpmfusion_free: yes
    rpmfusion_nonfree: no
    desktop_environment: gnome
  tasks:
    - name: Ensure SELinux Enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Enable container_manage_cgroup for running systemd in podman containers
      seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true

    - name: Set powersave when configuring a laptop
      when: ansible_form_factor in mobile_form_factors
      block:

        - name: Ensure powertop service enabled
          service:
            name: powertop
            enabled: true

        - name: Ensure powertop service started (only when not plugged in)
          service:
            name: powertop
            state: started
          when: "'discharging' in lookup('pipe', 'upower -i /org/freedesktop/UPower/devices/battery_BAT0')"

    - name: Disable ssh and rpcbind because reasons
      systemd:
        name: "{{ item }}"
        state: stopped
        masked: true
        enabled: false
      loop:
        - sshd
        - rpcbind

    - name: Ensure various ports are not open
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - cockpit
        - ssh

    - name: enable journald persistent storage
      file:
        path: /var/log/journal
        state: directory

    - name: workaround suspend issue on starlite mk3 laptop
      block:
        - name: install workaroundsuspend.service
          copy:
            src: files/starlite_mk3_suspendfix.service
            dest: /etc/systemd/system/workaroundsuspend.service
        - name: enable custom systemd unit
          systemd:
            name: workaroundsuspend.service
            daemon_reload: true
            enabled: true
            state: started
      when: ansible_hostname == 'starlite'

- name: User Stuff
  hosts: localhost
  become_user: admiller
  become: yes
  tasks:
    - name: import user dev stuff
      import_tasks: include_tasks/user_stuff.yml
    - name: import common flatpak app install set
      import_tasks: include_tasks/flatpak_common.yml
    - name: import gnome flatpak app install set
      import_tasks: include_tasks/flatpak_gnome.yml 

