---
- name: Fedora 31 XFCE Spin - System Stuff
  hosts: localhost
  vars:
    non_root_user: admiller
  tasks:
    - name: Package Install
      yum:
        state: present
        name:
          - tmux
          - xsel
          - irssi
          - mutt
          - git
          - tig
          - vim-enhanced
          - jq
          - python3
          - python3-devel
          - python3-virtualenv
          - bpftrace
          - bpftool
          - bcc
          - bcc-tools
          - python3-bcc
          - ruby
          - nodejs
          - golang
          - gcc
          - gcc-c++
          - automake
          - autoconf
          - make
          - libtool
          - setools-console
          - policycoreutils-python-utils
          - setroubleshoot-server
          - krb5-workstation
          - pcp-system-tools
          - lm_sensors
          - tuned
          - tuned-utils
          - powertop
          - iotop
          - procps-ng
          - firewalld
          - python3-firewall
          - aide
          - podman
          - podman-docker
          - buildah
          - skopeo
          - virt-manager
          - virt-viewer
          - redshift
          - redshift-gtk
          - mock
          - htop
          - glances
          - NetworkManager-openvpn
          - fedpkg
          - fpaste
          - mosh
          - flamegraph
          - fuse-overlayfs
          - podman
          - podman-docker
          - buildah
          - skopeo
          - fwupd
          - f31-backgrounds-xfce
          - f31-backgrounds-extras-xfce
          - xfce4-screensaver
          - xfce4-panel-profiles
          - '@rpm-development-tools'

    - name: Package Removal
      yum:
        state: absent
        name:
          - xscreensaver*

    - name: Ensure SELinux Enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Enable container_manage_cgroup for running systemd in podman containers
      seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true

    - name: U2F Token udev rules
      copy:
        src: files/70-u2f.rules
        dest: /etc/udev/rules.d/70-u2f.rules
      notify:
        - reload udev

    # This is a mild lie, we're going to move the file and the check will pass
    # on subsequent runs
    - name: Setup AIDE
      shell: aide --init
      args:
        creates: /var/lib/aide/aide.db.gz

    - name: Check for new AIDE database
      stat:
        path: /var/lib/aide/aide.db.new.gz
      register: new_aidedb_stat
      changed_when: false

    - name: Move new AIDE database if necessary
      copy:
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz
        remote_src: true
      when: "new_aidedb_stat['stat']['exists'] is defined and new_aidedb_stat['stat']['exists']"

    - name: Set AIDE cronjob
      cron:
        name: 'aide_check'
        hour: '4'
        user: 'root'
        job: "/usr/sbin/aide --check"

    - name: Create powertop2tuned tuned profile
      shell: powertop2tuned --enable powertop2tuned
      args:
        creates: /etc/tuned/powertop2tuned/tuned.conf

    - name: Get tuned profile
      slurp:
        src: /etc/tuned/active_profile
      register: tuned_active_profile

    - debug:
        msg: "{{ tuned_active_profile['content'] | b64decode | trim }}"

    - name: tuned-adm set powertop2tuned
      shell: /usr/sbin/tuned-adm profile powertop2tuned
      when: "tuned_active_profile['content'] | b64decode | trim != 'powertop2tuned'"

    - name: Apply iwlwifi settings
      copy:
        src: files/iwlwifi.conf
        dest: /etc/modprobe.d/iwlwifi.conf

    - name: Set container registry settings
      copy:
        src: files/registries.conf
        dest: /etc/containers/registries.conf

    - name: Disable ssh because reasons
      service:
        name: sshd
        state: stopped
        enabled: false

    - name: Ensure various ports are not open
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - cockpit
        - ssh

    - name: Make sure admiller user is in mock
      user:
        name: admiller
        groups: mock
        append: yes

    - name: Allow non-root user access to libvirt via polkit
      template:
        src: templates/non_root_user_libvirt_polkit.j2
        dest: /etc/polkit-1/rules.d/50-org.libvirt.unix.manage.rules
      notify:
        - reload polkit

    - name: Allow non-root user access to NetworkManager
      template:
        src: templates/network_manager_polkit.j2
        dest: /etc/polkit-1/rules.d/10-network-manager.pkla
      notify:
        - reload polkit

    - name: enable journald persistent storage
      file:
        path: /var/log/journal
        state: directory

    - name: enable GSSAPI for Chrome
      file:
        path: /etc/opt/chrome/policies/managed
        state: directory

    - name: config RHT SSO GSSAPI for Chrome
      copy:
        src: files/chrome_rht_gssapi_sso.json
        dest: /etc/opt/chrome/policies/managed/redhat-corp.json

  handlers:
    - name: reload udev
      shell: /usr/sbin/udevadm control --reload
    - name: reload polkit
      service:
        name: polkit
        state: restarted

- name: Fedora 31 XFCE Spin - User Stuff
  hosts: localhost
  become_user: admiller
  become: yes
  vars:
    xfce4_panel_profile: admiller_xfce4_4.14_panel_profile.tar.bz2
    xfce4_panel_profile_dest: "/home/{{ ansible_user_id }}/{{ xfce4_panel_profile }}"
  tasks:
    - name: import user dev stuff
      import_tasks: include_tasks/user_stuff.yml

    - name: copy xfce4-panel-profile backup
      copy:
        src: "files/{{ xfce4_panel_profile }}"
        dest: "{{ xfce4_panel_profile_dest }}"

    - name: load xfce4-panel-profile
      shell: xfce4-panel-profiles load "{{ xfce4_panel_profile_dest }}"

    - name: xfconf settings
      block:

        - name: set xflock4 to xscreensaver
          shell: xfconf-query -c xfce4-session -p /general/LockCommand -t string -s 'xfce4-screensaver-command -l'

        - name: don't hand over control of laptop lid to logind
          shell: xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/logind-handle-lid-switch -s false

        - name: set background
          shell: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s "/usr/share/backgrounds/f31/extras/galactic-mountains.jpg"

        - name: set Greybird theme
          shell: xfconf-query -c xfwm4 -p /general/theme -s "Greybird"

        - name: disable user switching in xfce4-screensaver
          shell: xfconf-query -c xfce4-screensaver -p /lock/user-switching/enabled -s false

        - name: set cursor theme to Adwaita
          shell: xfconf-query -c xsettings -p /Gtk/CursorThemeName -s Adwaita

