# gnome.yml
#
# Ansible playbook for configuring a laptop the way I like it and a little for
# work.
#
#

- name: Fedora Package Install - headless
  hosts: workstation
  user: root
  vars_files:
    - varfiles/workstation_vars.yml
  tasks:
    - import_tasks: tasks/pkginstall-generic.yml
    - import_tasks: tasks/groupinstall.yml
    - import_tasks: tasks/sysconf.yml
      tags: sysconf
    - import_tasks: tasks/userconf.yml
      tags:
        - userconf
    - import_role: fail2ban

# vim:ft=ansible:
