---

roles:
  # Install a role from Ansible Galaxy
  - name: geerlingguy.repo-epel
  - name: robertdebock.rpmfusion
  - name: jaredhocutt.brave_browser

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
