---
- name: RHEL8 Workstation / Server w/ GUI Setup / Laptop / Whatever
  hosts: localhost
  tasks:
    - name: Package Install
      yum:
        state: installed
        name:
          - tmux
          - git
          - vim-enhanced
          - jq
          - python36
          - python3-virtualenv
          - ruby
          - nodejs
          - gcc
          - gcc-c++
          - automake
          - autoconf
          - make
          - libtool
          - setools-console
          - policycoreutils-python-utils
          - setroubleshoot-server
          - gnome-tweaks
          - krb5-workstation
          - pcp-system-tools
          - lm_sensors
          - tuned
          - tuned-utils
          - powertop
          - crypto-policies
          - firewalld
          - python3-firewall
          - aide
          - podman
          - podman-docker
          - buildah
          - skopeo
          - virt-manager
          - '@rpm-development-tools'
          - '@go-toolset:rhel8'
          - '@container-tools:rhel8'

    - name: Ensure SELinux Enforcing
      selinux:
        policy: targeted
        state: enforcing

    - name: Enable container_manage_cgroup for running systemd in podman containers
      seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true

    - name: U2F Token udev rules
      copy:
        src: files/70-u2f.rules
        dest: /etc/udev/rules.d/70-u2f.rules
      notify:
        - reload udev

    - name: Check crypto policies
      shell: update-crypto-policies --show
      changed_when: false
      register: crypto_policies

    # should upgrade to FUTURE, but then RHN doesn't work because metadata
    # checksum is too weak
    - name: Set crypto policies to DEFAULT
      shell: update-crypto-policies --set DEFAULT
      when: "crypto_policies['stdout'] != 'DEFAULT'"

    # This is a mild lie, we're going to move the file and the check will pass
    # on subsequent runs
    - name: Setup AIDE
      shell: aide --init
      args:
        creates: /var/lib/aide/aide.db.gz

    - name: Check for new AIDE database
      stat:
        path: /var/lib/aide/aide.db.new.gz
      register: new_aidedb_stat
      changed_when: false

    - name: Move new AIDE database if necessary
      copy:
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz
        remote_src: true
      when: "new_aidedb_stat['stat']['exists'] is defined and new_aidedb_stat['stat']['exists']"

    - name: Set AIDE cronjob
      cron:
        name: 'aide_check'
        hour: '4'
        user: 'root'
        job: "/usr/sbin/aide --check"

    - name: Create powertop2tuned tuned profile
      shell: powertop2tuned --enable powertop2tuned
      args:
        creates: /etc/tuned/powertop2tuned/tuned.conf

    - name: Get tuned profile
      slurp:
        src: /etc/tuned/active_profile
      register: tuned_active_profile

    - debug:
        msg: "{{ tuned_active_profile['content'] | b64decode | trim }}"

    - name: tuned-adm set powertop2tuned
      shell: /usr/sbin/tuned-adm profile powertop2tuned
      when: "tuned_active_profile['content'] | b64decode | trim != 'powertop2tuned'"

    - name: Apply iwlwifi settings
      copy:
        src: files/iwlwifi.conf
        dest: /etc/modprobe.d/iwlwifi.conf

    - name: Set container registry settings
      copy:
        src: files/registries.conf
        dest: /etc/containers/registries.conf

    - name: Disable ssh because reasons
      service:
        name: sshd
        state: stopped
        enabled: false

    - name: Ensure various ports are not open
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - cockpit
        - ssh

  handlers:
    - name: reload udev
      shell: /usr/sbin/udevadm control --reload

- name: RHEL8 Workstation / Server w/ GUI Setup / Laptop / Whatever - User Stuff
  hosts: localhost
  become_user: admiller
  become: yes
  tasks:
    - name: pip user install some stuff
      pip:
        state: present
        name:
          - ptpython
          - virtualenvwrapper
          - httpie
          - flake8
          - pep8
          - pyflakes
          - pylint
          - q
        executable: 'pip3'
        extra_args: '--user'
    - name: gem user install tmuxinator
      gem:
        state: present
        name: tmuxinator
        user_install: yes
