---
- name: RHEL8 Workstation / Server w/ GUI Setup / Laptop / Whatever
  hosts: localhost
  tasks:
    - name: Package Install
      yum:
        state: installed
        name:
          - tmux
          - git
          - python36
          - python3-virtualenv
          - ruby
          - nodejs
          - gcc
          - gcc-c++
          - automake
          - autoconf
          - make
          - setools-console
          - policycoreutils-python-utils
          - gnome-tweaks
          - krb5-workstation
          - pcp-system-tools
          - lm_sensors
          - tuned-utils
          - '@rpm-development-tools'
          - '@go-toolset:rhel8'
          - '@container-tools:rhel8'

    - name: U2F Token udev rules
      copy:
        src: files/70-u2f.rules
        dest: /etc/udev/rules.d/70-u2f.rules
      notify:
        - reload udev

    - name: Create powertop2tuned tuned profile
      shell: powertop2tuned --enable powertop2tuned
      args:
        creates: /etc/tuned/powertop2tuned/tuned.conf

    - name: Get tuned profile
      slurp:
        src: /etc/tuned/active_profile
      register: tuned_active_profile

    - debug:
        msg: "{{ tuned_active_profile['content'] | b64decode | trim }}"

    - name: tuned-adm set powertop2tuned
      shell: /usr/sbin/tuned-adm profile powertop2tuned
      when: "tuned_active_profile['content'] | b64decode | trim != 'powertop2tuned'"

    - name: Apply iwlwifi settings
      copy:
        src: files/iwlwifi.conf
        dest: /etc/modprobe.d/iwlwifi.conf

  handlers:
    - name: reload udev
      shell: /usr/sbin/udevadm control --reload

