---
- name: CentOS Stream 9 Workstation / Server w/ GUI Setup / Laptop / Whatever
  hosts: localhost 
  vars:
    non_root_user: admiller
    flatpak_method: system
  tasks:

    - name: Package Install - CentOS Stream 9
      ansible.builtin.yum:
        state: installed
        name: "{{ packages_stream9 }}"

    - name: Package Install - Common
      ansible.builtin.yum:
        state: installed
        name: "{{ packages_common }}"

    - name: Package Install - Desktop
      ansible.builtin.yum:
        state: installed
        name: 
          - gnome-tweaks
          - gnome-shell-extension-windowsNavigator

    - name: Package Install - EPEL9 
      ansible.builtin.yum:
        state: installed
        name: "{{ packages_epel9 }}"

    - name: Setup CSB Repo
      template:
        src: templates/rhel8-csb.repo.j2
        dest: /etc/yum.repos.d/rhel8-csb.repo

    - name: Package Install - CSB RHEL8
      ansible.builtin.yum:
        state: installed
        name:
          #- oneplay-gstreamer-codecs-pack
          #- ffmpeg-libs
          - redhat-internal-openvpn-profiles
          - redhat-internal-NetworkManager-openvpn-profiles
          - redhat-internal-NetworkManager-openvpn-profiles-non-gnome
          - redhat-internal-wireless-config
          - redhat-internal-cert-install
      ignore_errors: yes

    - name: import flatpak app install tasks
      import_tasks: include_tasks/flatpak_install.yml

    - name: Ensure SELinux Enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    - name: Enable container_manage_cgroup for running systemd in podman containers
      ansible.posix.seboolean:
        name: container_manage_cgroup
        state: true
        persistent: true

    - name: Check crypto policies
      ansible.builtin.shell: update-crypto-policies --show
      changed_when: false
      register: crypto_policies

    # should upgrade to FUTURE, but then RHN doesn't work because metadata
    # checksum is too weak
    - name: Set crypto policies to DEFAULT
      ansible.builtin.shell: update-crypto-policies --set DEFAULT
      when: "crypto_policies['stdout'] != 'DEFAULT'"

    - name: Set laptop specific configurations
      when: ansible_form_factor in mobile_form_factors
      block:

        - name: Ensure powertop service enabled
          service:
            name: powertop
            enabled: true

        - name: Ensure powertop service started (only when not plugged in)
          service:
            name: powertop
            state: started
          when: "'discharging' in lookup('pipe', 'upower -i /org/freedesktop/UPower/devices/battery_BAT1')"

        - name: Apply iwlwifi settings
          copy:
            src: files/iwlwifi.conf
            dest: /etc/modprobe.d/iwlwifi.conf

    - name: force Xorg, Wayland still has a ways to go :(
      ansible.builtin.copy:
        src: files/etc_gdm_custom.conf
        dest: /etc/gdm/custom.conf

    - name: Disable ssh and rpcbind because reasons
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        masked: true
        enabled: false
      loop:
        - rpcbind
        - sshd

    - name: Ensure various ports are not open
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - cockpit
        - ssh

# FIXME - mock isn't in epel9 yet
#    - name: Make sure non_root_user user is in mock
#      ansible.builtin.user:
#        name: "{{ non_root_user }}" 
#        groups: mock
#        append: yes

    - name: Allow non-root user access to libvirt via polkit
      ansible.builtin.template:
        src: templates/non_root_user_libvirt_polkit.j2
        dest: /etc/polkit-1/rules.d/50-org.libvirt.unix.manage.rules
      notify:
        - reload polkit

    - name: Allow non-root user access to NetworkManager
      ansible.builtin.template:
        src: templates/network_manager_polkit.j2
        dest: /etc/polkit-1/rules.d/10-network-manager.pkla
      notify:
        - reload polkit

    - name: enable journald persistent storage
      ansible.builtin.file:
        path: /var/log/journal
        state: directory

# FIXME - boinc-client isn't in epel9 yet
#    - name: setup BOINC client for world community grid when it's not a laptop
#      ansible.builtin.import_role:
#        name: worldcommunitygrid
#      when: ansible_form_factor not in mobile_form_factors

  handlers:
    - name: reload polkit
      ansible.builtin.service:
        name: polkit
        state: restarted

- name: CentOS Stream 9 Workstation / Server w/ GUI Setup / Laptop / Whatever - User Stuff
  hosts: localhost
  become_user: admiller
  become: yes
  tasks:
    - name: import user dev stuff
      ansible.builtin.import_tasks: include_tasks/user_stuff.yml
    - name: import install minikube task set
      ansible.builtin.import_tasks: include_tasks/install_minikube.yml
