- name: Fedora toolbox
  hosts: localhost
  become: true
  tasks:

    - name: setup GH cli repo
      shell: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      args:
        creates: /etc/yum.repos.d/gh-cli.repo

    - name: Package Install - GitHub
      yum:
        state: installed
        name: 
          - gh

    - name: Package Install - Fedora
      yum:
        state: installed
        name: 
          - weechat
          - python3
          - python3-devel
          - golang
          - golang-x-tools-gopls
          - golang-x-tools-guru
          - htop
          - mosh
          - tig
          - fedpkg
          - fpaste
          - fedfind
          - ack
          - smartmontools
          - selinux-policy-doc
          - ShellCheck
          - glances
          - libvirt-client
          - tldr

    - name: Package Install - Common
      yum:
        state: installed
        name: "{{ packages_common }}"


