- name: Fedora toolbox
  hosts: localhost
  become: true
  tasks:
    - name: Package Install - Fedora
      yum:
        state: installed
        name: 
          - weechat
          - python3
          - python3-devel
          - golang
          - golang-x-tools-gopls
          - htop
          - mosh
          - tig
          - fedpkg
          - fpaste
          - fedfind
          - ack
          - smartmontools
          - selinux-policy-doc
          - ShellCheck
          - glances

    - name: Package Install - Common
      yum:
        state: installed
        name: "{{ packages_common }}"

