- name: Verify powertop is installed
  dnf:
    state: installed
    name: powertop

- name: Start and enable powertop.service
  service:
    name: powertop
    state: started
    enabled: yes


# vim:ft=yaml.ansible