---
#

- name: Install httpd for resume hosting
  dnf:
    state: installed
    name:
      - httpd
      - mod_ssl
      - python-certbot-apache

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Upload resume
  copy:
    src: resume
    dest: /var/www/html/resume



# vim:ft=ansible: