---
# main.yml - Common Tasks for maxamillion.sh
#

- import_tasks: prereqs.yml
- import_tasks: selinux.yml
- import_tasks: pkginstall.yml
- import_tasks: timedatectl.yml
- import_tasks: sshd.yml
  when: deployment_type != "workstation"


# vim:ft=yaml.ansible