---
# prereqs.yml
# - install packages for other functionality not in minimal
#   RHEL/CentOS/Fedora installs
- name: Install Packages
  dnf:
    state: installed
    name:
      - python-keyczar
      - yum-utils
      - python-simplejson
      - libselinux-python


# vim:ft=ansible: