---
# main.yml - configure tuned
#

- name: Install dnf packages
  dnf:
    state: installed
    name:
      - tuned
      - tuned-utils-systemtap

- name: Start and Enable tuned
  service:
    name: tuned
    state: started
    enabled: yes


# vim:ft=ansible: